const path = require('path');
console.log('-'.repeat(80));
console.log('__filename:', __filename);
console.log('__dirname:', __dirname);
console.log('-'.repeat(80));
console.log('path.sep:', path.sep);
console.log('path.delimiter:', path.delimiter);
console.log('-'.repeat(80));
console.log('path.dirname(__filename):', path.dirname(__filename));
console.log('path.extname(__filename):', path.extname(__filename));
console.log('path.basename(__filename):', path.basename(__filename));
console.log('path.basename(__filename, path.extname(__filename)):', path.basename(__filename, path.extname(__filename)));
console.log('-'.repeat(80));
console.log('path.parse(__filename):', path.parse(__filename));
console.log('path.format(path.parse(__filename)):', path.format(path.parse(__filename)));
console.log('path.normalize(__filename):', path.normalize(__filename));
console.log('-'.repeat(80));
console.log('path.isAbsolute(__filename):', path.isAbsolute(__filename));
console.log('path.relative(__filename, "/Users/c11g/study"):', path.relative(__filename, '/Users/c11g/study'));
console.log('-'.repeat(80));
console.log('path.join(__dirname, path.basename(__filename)):', path.join(__dirname, path.basename(__filename)));
console.log('path.resolve(__dirname, path.basename(__filename)):', path.resolve(__dirname, path.basename(__filename)));
console.log('path.join("/a", "/b", "c"):', path.join("/a", "/b", "c"));
console.log('path.resolve("/a", "/b", "c"):', path.resolve("/a", "/b", "c"));